### ISSUE TITLE
aaron wil graag de oude pinball physics terug

### ISSUE THREAD

**Issue by Vivaloz** [JelNet-webapplications/PinballPhysics#2]
wat dacht je van een geheim command? Kan ik wel programmeren

**Comment by volt64bolt** [comment]
Sure go ahead, it's written in java script and using p5 for the main visuals. What feature were you thinking?

Ga je gang, het is geschreven in javascript en gebruikt p5 voor de belangrijkste beelden. Aan welke functie dacht je?

**Comment by volt64bolt** [comment]
Wrong button

**Comment by Vivaloz** [comment]
voordat we deze pinball physics pagina hadden was er nog een oudere, eentje met alleen maar de pinballs ipv van die lichtstralen, magneten enz

aaron gebruikte die altijd ipv van de huidige met de teringrare link waarmee die pagina stiekem nog op de website stond maar jelle heeft m verwijderd 

@JelCraft kan je die ouwe er terug opzetten? gwn als `https://jelcraft.tk/pinball-physics-old/`, dan zorg ik wel voor de code voor een command (denk zelf alt+shift+o met de "o" van "oud")

**Comment by volt64bolt** [comment]
You can disable all the extra features on the current one, just turn the light rays to 0 and magnet off.

**Comment by Vivaloz** [comment]
it's not the same and moreover the pinballs are barely visible at light ray 0

**Comment by volt64bolt** [comment]
Ohhhhhhhhh I must not have added the code for the light switch, I will add that to the main file later today

**Comment by Vivaloz** [comment]
i don't know if you are aware of the old pinball physics (perhaps it was even you who created it) but there's old an other version which jelcraft has to put back on the server

**Comment by volt64bolt** [comment]
I made all of this. Jel did like 1 feature, the rest was all me. The very first version jel put on there was V0, if you want I can create a toggle to just switch between the old and new UI

**Comment by JelCraft** [comment]
Ik zou de oude er wel weer op kunnen zetten maar we kunnen beter deze versie gwn houden met, zoals volt zei, een lichtknopje om de rays helemaal uit te zetten.

Volt heeft alle versies van pinballphysics gemaakt

**Comment by JelCraft** [comment]
> I made all of this. Jel did like 1 feature, the rest was all me. The very first version jel put on there was V0, if you want I can create a toggle to just switch between the old and new UI

Maar dit klinkt imo als de beste oplossing ja, dan kan volt daarmee aan de slag

**Comment by volt64bolt** [comment]
as of the Advanced-options-switch-test branch a button to open the advanced options menu has been added. By default light rays, magnet, and all other future advanced options are disabled and hidden.
