### ISSUE TITLE
If submit is pressed, but the amount has not been updated, automatically add the previous amount to the counter.

### ISSUE THREAD

**Issue by JelCraft** [JelNet-webapplications/PinballPhysics#4]
If the submit button is pressed without any changes to the number of pinballs in the input field, the previous operation should be repeated.

E.g. 
First button press, `input = 100`,  
Second button press, `input += 100`
Third button press `input += 100`, instead of `input += input`, because this will cause the amount to rise exponentially.

I guess this could be done by storing an "operation" value, which is the last known value of the input field, which is not updated by repeated button pressess. The input field itself should of course visually update, so the sum in the input still correlates to the amount of rendered pinballs.

**Comment by volt64bolt** [comment]
I don't quite get what you mean, currently the amount set is the amount shown, if it increases it adds extra to get to the new amount, and if it decreases it removes some to get to that amount. This was to keep it more inline with your non-physics version where it shows how many you can get.

**Comment by JelCraft** [comment]
What I'm basically referring to is the same behaviour on most calculators. Pressing the ans button multiple times repeats the operation.
If you click the submit button multiple times it would be cool to have the amount in the input field increase

**Comment by volt64bolt** [comment]
Ohhh ok I think I get you.... Idk how I can make that work efficiently though but I will try

**Comment by volt64bolt** [comment]
This is now added into the branch of advanced-options-switch-test and will be merged after testing
